---
- hosts: all
  remote_user: root

  tasks:
    - name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

    - name: Allow new incoming SYN packets on TCP port 8080
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
    - name: Allow new incoming SYN packets on TCP port 1834
    
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 1834
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
    
    - name: Allow new incoming SYN packets on TCP port 22 (SSH)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
