---
- hosts: all
  remote_user: root

  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
      - name: Upgrade all apt packages
      yum: upgrade=dist force_apt_get=yes
  when: ansible_distribution == 'CentOS' 
